from __future__ import annotations

from typing import Any, Mapping, Protocol

import numpy as np


class SubstrateProtocol(Protocol):
    name: str

    def reset(self, config: dict[str, Any], seed: int) -> None: ...

    def step(self, n: int = 1) -> None: ...

    def render_frame(self) -> np.ndarray: ...

    def get_state(self) -> dict[str, Any]: ...

    def set_state(self, state: dict[str, Any]) -> None: ...

    def extract_metrics(self) -> dict[str, float]: ...

    def apply_perturbation(self, perturbation: dict[str, Any]) -> None: ...

    def is_extinct(self) -> bool: ...


class SearchModeProtocol(Protocol):
    name: str

    def objective_weights(self) -> Mapping[str, float]: ...

    def preferred_archive(self) -> str: ...

    def validation_threshold(self) -> float: ...

    def archive_threshold(self) -> float: ...
